[package]
name = "genetic_algorithm"
version = "0.3.1"
edition = "2021"
readme = "README.md"
rust-version = "1.60"
description = "A genetic algorithm implementation"
repository = "https://github.com/basvanwesting/genetic-algorithm.git"
homepage = "https://github.com/basvanwesting/genetic-algorithm.git"
documentation = "https://docs.rs/genetic_algorithm/latest/genetic_algorithm"
license-file = "LICENSE"
keywords = ["genetic", "ga"]
exclude = ["/.projections.json", "/performance.txt", "/refactor_script.rb", "/workspace.txt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
itertools = "0.10.3"
streaming-stats = "0.2.3"
factorial = "0.2.1"
num = "0.4.0"

[dev-dependencies]
lru = "0.7.5"
criterion = "0.3"
pprof = { version = "0.7", features = ["criterion", "flamegraph"] }
distance = "0.4.0"

[[bench]]
name = "fitness"
harness = false

[[bench]]
name = "compete"
harness = false

[[bench]]
name = "crossover"
harness = false

[[bench]]
name = "genotype"
harness = false

[[bench]]
name = "evolve"
harness = false
